### PR TITLE
Mail2kvanitha/readmes

### PR DESCRIPTION
**Pull request by mail2kvanitha**
Added Table of Contents to Readme.md and Formatted basic skeleton for Readme.md

### CODE REVIEW

**Review by mail2kvanitha — COMMENTED** [review]
Updates to README.md file 
Added skeleton to the file,
Added Table of Contents to the file.

**Review by frdvo — DISMISSED** [review]
lgtm

**Review by mail2kvanitha — COMMENTED** [review]
Replaced all Capital Letters for headings.

**Comment by jayanath** [comment]
We have some conflicts 💣 to resolve.

**Comment by mail2kvanitha** [comment]
Please check now.The conflicts are resolved.

**Review by mail2kvanitha — COMMENTED** [review]
Please check now, resolved all the conflicts

**Review by jayanath — APPROVED** [review]
Nice!👍

**Pull request merged**
